on:
  #pull_request:
  push:
    # Sequence of patterns matched against refs/tags    
name: Create Release and Upload Asset

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Actions Ecosystem Action Regex Match
        uses: actions-ecosystem/action-regex-match@v2.0.2
        id: regex-match
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '\[(bug|feature|major)\]'
      - name: Find Tag Version
        uses: salsify/action-detect-and-tag-new-version@v2
        id: tag_version
        with:
          version-command: |
            cat VERSION
      - name: Increment Semantic Version
        uses: christian-draeger/increment-semantic-version@1.0.2
        id: bump_version
        with:
          current-version: ${{ steps.tag_version.outputs.current-version }}
          version-fragment: ${{ steps.regex-match.outputs.group1 }}
      - name: Update version in VERSION file
        run: |
          echo ${{ steps.bump_version.outputs.next-version }} > VERSION
      - name: Update package.json version
        uses: jossef/action-set-json-field@v1
        with:
          file: package.json
          field: version
          value: ${{ steps.bump_version.outputs.next-version }}
      - name: Update system.json version
        uses: jossef/action-set-json-field@v1
        with:
          file: system.json
          field: version
          value: ${{ steps.bump_version.outputs.next-version }}
      - name: Get JSON Property
        id: download_version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'system.json'
          prop_path: 'download'
      - name: Update download path
        uses: frabert/replace-string-action@v2.0
        id: update_path
        with:
          pattern: '(https:\/\/github\.com\/Shaf074\/shazhack\/releases\/download\/)[0-9.]{5}(\/shazhack-main\.zip)'
          string: '${{ steps.download_version.outputs.prop }}'
          replace-with: '$1${{ steps.bump_version.outputs.next-version }}$2'
      - name: Update system.json version
        uses: jossef/action-set-json-field@v1
        with:
          file: system.json
          field: download
          value: ${{ steps.update_path.outputs.replaced }}
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          zip --recurse-paths shazhack-main *
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump_version.outputs.next-version }}
          release_name: Release ${{ steps.bump_version.outputs.next-version }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./shazhack-main.zip
          asset_name: shazhack-main.zip
          asset_content_type: application/zip
